[package]
name = "btd"
version = "1.0.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
edit = "0.1.5"
open = "5.1.2"
regex = "1.10.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"
system = "0.3.0"
